### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by krthr** [harlan-zw/nuxt-delay-hydration#1]
**Is your feature request related to a problem? Please describe.**
I tested the library in "mount" mode, but some scripts do not load in Safari because Safari does not yet support `window.requestIdleCallback()` :( 

**Describe the solution you'd like**
- Add a warning in the README
- Use polyfills (?

**Describe alternatives you've considered**
-

**Additional context**
I include screenshots to show the exception:
- https://massivemonster.co/
<img width="666" alt="Captura de Pantalla 2021-08-28 a la(s) 3 35 58 p m" src="https://user-images.githubusercontent.com/18665740/131230417-f20d9fd2-5fbb-4e4c-967a-287231418df6.png">

**Comment by mvrlin** [comment]
@krthr https://github.com/pladaria/requestidlecallback-polyfill working with that

**Comment by harlan-zw** [comment]
Hey @krthr & @mvrlin 

The testing was a bit annoying for it, but it should be fixed. If the browser doesn't support `requestIdleCallback` then it won't run the delay at all, which shouldn't be an issue.

Would you mind re-testing for me then I can close this ticket off :)?

**Comment by mvrlin** [comment]
@harlan-zw Working great, thanks!
