### ISSUE TITLE
Google lighthouse mobile performance error Nuxt.js ^2.2.0

### ISSUE THREAD

**Issue by ybabenkoJapp** [harlan-zw/nuxt-delay-hydration#10]
**Describe the bug**
Hi guys! I implemented your excellent nuxt-delay-hydration module in my project. I tried to use modes: init, and mount. All worked as expected, but Google lighthouse wasn't able to check performance for mobile for both of mentioned modes. 

```
 buildModules: [
    '@nuxt/typescript-build',
    '@nuxt-hero-icons/solid/nuxt',
    'nuxt-compress',
    'nuxt-delay-hydration',
  ],
  delayHydration: {
    mode: 'mount',
  },

"dependencies": {
    "@nuxt-hero-icons/solid": "^1.0.1",
    "@nuxt/typescript-runtime": "^0.4.10",
    "@nuxtjs/axios": "^5.11.0",
    "@nuxtjs/robots": "^2.4.2",
    "@nuxtjs/sitemap": "^2.4.0",
    "nuxt": "^2.2.0",
    "nuxt-delay-hydration": "^0.4.5",
    "nuxt-font-loader-strategy": "^1.1.9",
    "nuxt-lazy-load": "^1.2.9",
    "standard-version": "^8.0.1",
    "storyblok-nuxt": "^1.2.0",
    "swiper": "^7.0.9",
    "vue-class-component": "^7.2.3",
    "vue-fragment": "^1.5.2",
    "vue-intersect-directive": "^1.1.1",
    "vue-lottie-player": "^0.1.9",
    "vue-pagination-2": "^3.0.91",
    "vue-property-decorator": "^9.0.0",
    "vue-range-slider": "^0.6.0",
    "vue-slider-component": "^3.2.15",
    "vuex": "^3.5.1"
  },
```

**To Reproduce**

The SSG project successfully builds without errors and hosting on netlify.

**Expected behavior**
Deployed website is supposed to check the performance of the lighthouse.
For the desktop, all is ok but not for the mobile.

**Screenshots**
<img width="1440" alt="mob" src="https://user-images.githubusercontent.com/84498280/198027289-e7a67d48-73b1-4a11-92f8-e36123f9218a.png">
<img width="1440" alt="desktop" src="https://user-images.githubusercontent.com/84498280/198027309-f63f79a6-c0af-4d8e-98c2-3cc8bcd154ac.png">

**Additional context**
If you need any additional information please ping me.

**Comment by harlan-zw** [comment]
Closing this issue as the Nuxt 2 module is deprecated and won't receive any new updates.
