### ISSUE TITLE
replay click doesn't work for touch events

### ISSUE THREAD

**Issue by oppianmatt** [harlan-zw/nuxt-delay-hydration#11]
**Describe the bug**

When using a mobile, the replay click event looks at the type of event, but since it is a touch event, it doesn't replay it

![image](https://user-images.githubusercontent.com/48596/199965905-090bbdd5-477e-4000-8b79-c413ceb19bdc.png)

**Comment by harlan-zw** [comment]
I've updated it to also check for the TouchEvent instance, not sure if this will fully support it but feel free to test.

Available in v0.4.6
