### ISSUE TITLE
setting hydrateOnEvents on does not override but merges

### ISSUE THREAD

**Issue by oppianmatt** [harlan-zw/nuxt-delay-hydration#12]
**Describe the bug**

When trying to set `hydrateOnEvents` it doesn't use the new value but merges it instead with the existing values

See the screenshot, have set it to to just click, but now see click plus the defaults.

![image](https://user-images.githubusercontent.com/48596/199976897-21db390d-b1e3-4e3a-bdc9-f4ab8b02bdba.png)

**Comment by harlan-zw** [comment]
Fixed in v0.4.6 :)
