### ISSUE TITLE
Can not import component at mode 'Manual'

### ISSUE THREAD

**Issue by chithien-pin** [harlan-zw/nuxt-delay-hydration#13]
**Describe the bug**
I read and follow the readme to use component _DelayHydration_ at _Manual Mode_ but when I run the program I get an error like the screenshots

**Screenshots**
![CleanShot 2022-11-23 at 12 48 16](https://user-images.githubusercontent.com/67494645/203479539-8cd11e85-ac68-4476-87d5-5c0e74934992.png)

<img width="1695" alt="CleanShot 2022-11-23 at 12 52 29@2x" src="https://user-images.githubusercontent.com/67494645/203480414-98803383-fb0a-4194-ac30-dff2db4e9a1e.png">

**Comment by savritsky** [comment]
I got it like this
import DelayHydration from 'nuxt-delay-hydration/dist/runtime/components/DelayHydration.vue'

**Comment by chithien-pin** [comment]
> I got it like this import DelayHydration from 'nuxt-delay-hydration/dist/runtime/components/DelayHydration.vue'

Thanks bro! your comment so helpfully!

**Comment by harlan-zw** [comment]
Thank you @savritsky 

Have updated the read me to this path.

**Comment by harlan-zw** [comment]
Looks like there was a bug in the auto imports too, fixed in version 0.4.7
