### ISSUE TITLE
Different between idleCallbackTimeout and postIdleTimeout

### ISSUE THREAD

**Issue by neetu1123** [harlan-zw/nuxt-delay-hydration#18]
Describe or difference between idleCallback Timeout and postIdle Timeout

**Comment by harlan-zw** [comment]
Hi @neetu1123 

Are you having issues with the [documentation](https://github.com/harlan-zw/nuxt-delay-hydration#idle-hydration) for them? 

Does this code sample help?

```ts
requestIdleCallback(() => {
   setTimeout(() => {
        // hydrate!
   }, postIdleTimeout)
}, { timeout: idleCallbackTimeout )
```

**Comment by neetu1123** [comment]
Thanks for replying
But , can you tell why we are giving different time for desktop and mobile ?
and why we have to also  give separate time for postIdleTimeout ?
 we can give  specific time in idleCallbackTimeout

**Comment by harlan-zw** [comment]
If you run logic straight after the idle callback it will be labelled as blocking, so we need to wait for some timeout period.

They're difference because the amount of time needed to wait for it not to be considered blocking varies on device.

**Comment by neetu1123** [comment]
Thanks for clear my doubt @harlan-zw
