### ISSUE TITLE
Error occuring in creating project build in nuxt 3

### ISSUE THREAD

**Issue by neerajnanvani** [harlan-zw/nuxt-delay-hydration#19]
**Describe the bug**
When we try to create the project build via **nuxt build**, we got an error of delayHydration is not a window property.

**To Reproduce**
1. Create a nuxt project 
2. Install nuxt-delay-hydration module.
3. Run npm run build / npx nuxt analyze 
4. See the error,

**Expected behavior**
There should be no error or warning

**Screenshots**
![image](https://user-images.githubusercontent.com/95841612/216241191-d74b5892-276b-4cf1-a803-0810fb73d0b3.png)

**Comment by harlan-zw** [comment]
Hey @neerajnanvani. Thanks for the issue!

Should be fixed in version 1.1.1
