### ISSUE TITLE
<force-hydration> (opposite of <delay-hydration>)

### ISSUE THREAD

**Issue by OfekA** [harlan-zw/nuxt-delay-hydration#2]
**Is your feature request related to a problem? Please describe.**
Wanting to use the 'init' or 'mount' mode, but need to force hydrating some components before the user interaction in some pages, specifically those that are above the fold.

**Describe the solution you'd like**
In 'init' or 'mount' mode, add the ability to select certain tree nodes that should hydrate as soon as possible, for example:

```js
<template>
    <div>
        <my-non-reactive-component />
        <force-hydration>
            <reactive-component />
        </force-hydration>
        <another-non-reactive-component />
    </div>
</template>
```

**Describe alternatives you've considered**
The only alternative that I could consider was using 'manual' mode, but this is very tedious and error-prone in a large website that mostly consists of static pages.

**Comment by harlan-zw** [comment]
Hey @OfekA 

I'd love to be able to build this feature, but I don't know how it would be possible with Vue 3 currently. It was hinted it would be available with Vue 3.1 but there isn't anything documented for it. (https://twitter.com/youyuxi/status/1307014320056799232?lang=en). See: https://markus.oberlehner.net/blog/partial-hydration-concepts-lazy-and-active/ 

Either way, Nuxt doesn't support Vue 3 so it wouldn't be possible. 

I'd recommend seeing if it's possible for your above the fold content to not require javascript before user interaction. If javascript is required then you are cheating Google essentially with this package.

Could you clarify how the manual mode is tedious and error-prone? You should just be able to add it to the layout, wrapping the static part of the layout.
