### ISSUE TITLE
Nuxt Fatal Error with ```npm run dev``` after installing the module

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [harlan-zw/nuxt-delay-hydration#25]
**Describe the bug**
nuxt simply won't run any scripts like ```dev``` , ```build``` , ```start``` after adding the library  to ```nuxt.config.js```
**To Reproduce**
Nuxt version ```  "nuxt": "^2.15.8" ```
- ```npm install nuxt-delay-hydration``` 
inside ```nuxt.config.js```  : 
```
 modules: [ 'nuxt-delay-hydration'],
   delayHydration: {
    debug: process.env.NODE_ENV === 'development',
    mode: 'init'
  },
```
**Expected behavior**
Run the server in development mode

**What happens:**

I get the following error : 
**screenshot**

![image](https://user-images.githubusercontent.com/40239163/218693510-c3e4b695-c182-4b9b-961a-397bd70e03b7.png)

**Comment by harlan-zw** [comment]
Can you confirm you're using version [v1.1.4](https://github.com/harlan-zw/nuxt-delay-hydration/releases/tag/v1.1.4), I might need to update the docs to make this clearer.

**Comment by abdurrahmanseyidoglu** [comment]
indeed Im using it
```"nuxt-delay-hydration": "^1.1.4",```

**Comment by harlan-zw** [comment]
Oops, I meant to say you should be using [v0.4.7](https://github.com/harlan-zw/nuxt-delay-hydration/releases/tag/v0.4.7)

**Comment by abdurrahmanseyidoglu** [comment]
unfortunately did not work 
here is a reproduction repo 
https://github.com/abdurrahmanseyidoglu/nuxt-delay-hydration-error

**Comment by abdurrahmanseyidoglu** [comment]
The problem was with my Node version ```12.22.3``` upgrading it to ```14.21.3``` fixed the issue for me
