### ISSUE TITLE
Uncaught (in promise) ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by den-kar** [harlan-zw/nuxt-delay-hydration#26]
**Describe the bug**
When loading `localhost:3000` after running `yarn dev` (or `yarn build` and `node .output/server/index.mjs`) on my private Nuxt 3 project, I get a the console error  message
> Uncaught (in promise) ReferenceError: TouchEvent is not defined

**To Reproduce**
This error messages does not show up on a fresh setup with `npx nuxi init new-project`, 'yarn install' and 'yarn add -D nuxt-delay-hydration`.

**Expected behavior**
No error log.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47293315/230576301-326774b8-6e03-4e0d-9f1b-b0e1550a83c2.png)

**Additional context**
_nuxt.config.ts_
```ts
export default defineNuxtConfig({
  ...
  modules: [
    ...
    'nuxt-delay-hydration',
    ...
  ],
  delayHydration: {
    mode: 'mount',
    debug: process.env.NUXT_ENV_DEV !== 'production',
  },
  ...
})
```
_package.json_
```json
  ...
  "devDependencies": {
    ...
    "nuxt": "^3.3.3",
    "nuxt-delay-hydration": "^1.1.4",
    ...
  },
  ...
```

**Possible bug fix**
Fixed by changing line 3 in node_modules/nuxt-delay-hydration/dist/replay.mjs,
from :
```js
if (!(e instanceof PointerEvent) && !(e instanceof MouseEvent) && !(e instanceof TouchEvent))
```
to:
```js
if (!(e instanceof PointerEvent) && !(e instanceof MouseEvent) && !(window.TouchEvent && e instanceof TouchEvent))
```

**Comment by dmashoshin** [comment]
Same here
