### ISSUE TITLE
Nuxt Fatal Error

### ISSUE THREAD

**Issue by hagi4u** [harlan-zw/nuxt-delay-hydration#27]
![image](https://user-images.githubusercontent.com/6129756/236709949-e6082442-4d58-49d6-8e46-0e62e18b0709.png)

I use to nuxt 2 and installed `"nuxt-delay-hydration": "^0.4.7"`
after then `npm run dev` I saw about Nuxt Fatal Error `TypeError: Invalid host defined options`

my typescript version is 4.6.2
how can i try to fix this problem?

**Comment by harlan-zw** [comment]
I think you tried using the v3 module in nuxt 2
