### ISSUE TITLE
Visualising the hydration status

### ISSUE THREAD

**Issue by webdev4422** [harlan-zw/nuxt-delay-hydration#3]
**Describe the bug**
<hydration-status /> component not working

**To Reproduce**
1. Add `<hydration-status />` component to default.vue layout.
2. Generate app with `yarn nuxt generate`.
3. Run app on localhost with nginx server.
3. No output on page, also no output in chrome devtools console.

**Expected behavior**
Any output from hydration status.

**Screenshots**
![image](https://user-images.githubusercontent.com/67459982/141503486-b7a2295b-9b7a-4b74-888a-c812598ec449.png)

**Additional context**

**Comment by harlan-zw** [comment]
this may be fixed, related to the component not being found 

let me know if you still have issues

**Comment by webdev4422** [comment]
Thank you for reply, still no output found.

**Comment by harlan-zw** [comment]
Sorry I found the bug, should be fixed in v0.4.7
