### ISSUE TITLE
hmr breaks using nuxt delay hydration

### ISSUE THREAD

**Issue by ThimoDEV** [harlan-zw/nuxt-delay-hydration#30]
**Describe the bug**
When I enable nuxt delay hydration in my project, hmr stops working

**To Reproduce**
1. Clone repository: https://github.com/ThimoDEV/nuxt-hmr-bug
2. Run: pnpm dev
3. See: When nuxt delay is enabled, hmr sytopps working

**Expected behavior**
Hmr working as normal

**Comment by harlan-zw** [comment]
Yes, this is expected, you should disable the `debug` mode once you have finished tested. I have updated the docs to make that clearer.
