### ISSUE TITLE
Service Worker is not registering on "init mode"

### ISSUE THREAD

**Issue by neetu1123** [harlan-zw/nuxt-delay-hydration#33]
**Describe the bug**
In the `init` mode, the service worker is not being registered properly. However, when using the `mount` mode, it functions correctly. I am utilizing the `register-service-worker@1.7.2` package, which includes a `register` method along with several hooks such as `registered`, `error` and `updated`. Unfortunately, none of these hooks are being triggered in the `init` mode.

**Expected behavior**
After a timeout of the delayed hydration process, the service worker should be registered properly.

**Reproduce Like**
https://github.com/neetu1123/Service_Worker

**Comment by harlan-zw** [comment]
This seems to be fixed now with the latest Nuxt version :thinking:
