### ISSUE TITLE
Can hydration delay be set only for mobile devices?

### ISSUE THREAD

**Issue by Red-Asuka** [harlan-zw/nuxt-delay-hydration#35]
**Is your feature request related to a problem? Please describe.**

This is a great module. In my testing, it significantly reduces TBT (Total Blocking Time) on mobile devices, but increases TBT on desktop devices. Lighthouse has stricter performance requirements for mobile than desktop. My website already achieves a score of 90+ on desktop, so I hope to only use delay hydration on mobile devices. Is it possible to add a setting to allow delay hydration to be enabled only on certain devices?

**Describe the solution you'd like**

settings like this: `devices: 'all' | 'mobile' | 'desktop'`

**Describe alternatives you've considered**

Or it can be eliminated by other means to reduce its impact on the desktop end.

**Additional context**

**Comment by Red-Asuka** [comment]
This is a temporary solution I have come up with for those in need. It is worth mentioning that using regular expressions as include and exclude options is ineffective. Upon examining the source code, I discovered that these options are first processed through JSON.stringify() before being passed along. However, when encountering a regular expression, JSON.stringify() converts it into an empty object {}. I took the opportunity to fix this bug as well.

```ts
// /server/plugins/html.render.ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event }) => {
    // Find script for delay hydration
    const index = html.bodyAppend.findIndex(item => item.includes('w._$delayHydration'))
    if (index === -1)
      return
    // Only use delay hydration on mobile devices
    html.bodyAppend[index] = html.bodyAppend[index].replace(
      /w\._\$delayHydration = \(\(\) => {/,
  `w._$delayHydration = (() => {
    const isMobile = window.innerWidth < 640;
    if (!isMobile) {
      return Promise.resolve("Not a mobile device")
    }`,
    )
    // Fix the issue of invalid delay hydration exclude.
    const path = event.path
    const exclude = [
      /^\/(en|zh|ja)\/(customers|community)($|\?|#)/,
    ]
    const isExclude = exclude.some(reg => reg.test(path))
    if (!isExclude)
      return
    html.bodyAppend.splice(index, 1)
  })
})

```

**Comment by tibineagu** [comment]
@Red-Asuka you could try to use the plugin in "manual" mode and use the `DelayHydration` component in combination with something like [`@nuxtjs/device`](https://nuxt.com/modules/device/)
