### ISSUE TITLE
ReferenceError: TouchEvent is not defined - happening with replayClick on Firefox for Mac

### ISSUE THREAD

**Issue by tibineagu** [harlan-zw/nuxt-delay-hydration#37]
**Describe the bug**
When using the module with `replayClick: true` on Firefox for Mac, the browser will throw a ReferenceError.
**ℹ️ This will only happen if the user does NOT trigger any of the events** that trigger early hydration (click, scroll, etc)

```
Uncaught (in promise) ReferenceError: TouchEvent is not defined
```

**To Reproduce**
1. Use the `delayHydration` module with nuxt v2 or v3
2. In the module's configuration, use `replayClick: true`
3. Access the page using Firefox on macOS but **do not interact with the page** in a way that would force an early hydration
4. After the hydration timeout, notice the error in the browser console
5. The hydration will be stopped, leaving the page in an unusable state

[Codesandbox link](https://codesandbox.io/p/sandbox/amazing-chihiro-f2yyq8)
[Direct browser access](https://f2yyq8-3000.csb.app/)
- Notice that if you do interact with the page before the timeout, the error will not appear in the console

**Expected behavior**
The error should not appear and the app should be hydrated as normally.

**Screenshots**
<img width="482" alt="image" src="https://github.com/harlan-zw/nuxt-delay-hydration/assets/441717/c6c4a523-c389-4a6a-8ce8-551bc6bae25d">

**Additional context**
I have traced the issue to [this line](https://github.com/harlan-zw/nuxt-delay-hydration/blob/865ee3b20b4b9ef715deb64c5a2a5713a2b72385/src/template/replay.ts#L3) (for v1), and [this line](https://github.com/harlan-zw/nuxt-delay-hydration/blob/7ad16b4a19de5e518498e664db0b49e8cd76b7bc/packages/nuxt-delay-hydration/src/runtime/template/replayPointerEvent.js#L7), respectively (for v0)

The `TouchEvent` issue seems to be a recurring Firefox for Mac problem, and it's been [reported on other libraries](https://github.com/scratchfoundation/scratch-gui/issues/1317) since 2018. The fix will likely be to check for the existence of `TouchEvent` before the `instanceof` clause.

**Comment by mbreit** [comment]
We've received reports of this error occurring across various versions of Firefox (117, 118, 119) and on multiple operating systems (Windows, macOS, and Linux). I have also been able to reproduce it on Linux with Firefox 119b7.

**Comment by mbreit** [comment]
Just deployed version 1.2.3 to production and cannot reproduce this issue anymore.

**Comment by tibineagu** [comment]
@harlan-zw can we trickle the fix down to the [nuxt 2 module](https://github.com/harlan-zw/nuxt-delay-hydration/blob/v1/packages/nuxt-delay-hydration/src/template/replay.ts#L3) as well please?

**Comment by tibineagu** [comment]
@mbreit @harlan-zw can we trickle the fix down to the [nuxt 2 module](https://github.com/harlan-zw/nuxt-delay-hydration/blob/v1/packages/nuxt-delay-hydration/src/template/replay.ts#L3) as well please?
