### ISSUE TITLE
'manual' mode does not work, behaves same like 'mount' mode

### ISSUE THREAD

**Issue by sauravbv** [harlan-zw/nuxt-delay-hydration#39]
**Describe the bug**
The `manual` mode does not work as intended from the docs. By wrapping one component with `<DelayHydration>` other elements are also delay hydrated. This is actually delay hydrating the entire application just like `mount` mode

**To Reproduce**
Please check the below stackblitz demo

There are two components and only one is wrapped with `<DelayHydration>` component, yet the logs from both are printed after the hydration event i.e. both are getting lazily hydrated.
https://stackblitz.com/edit/nuxt-starter-8agcnh?file=app.vue

Have tried with multiple versions of nuxt, node and package which might have helped for easier troubleshooting
**Nuxt version: 3.8.1 
Node version: 16, 18
Package version: 1.2.3, 1.2.2** 

**Expected behavior**
Only the components wrapped in `<DelayHydration>` should be lazily hydrated as intended.

**Screenshots**
<img width="1022" alt="image" src="https://github.com/harlan-zw/nuxt-delay-hydration/assets/41701284/e9c4b6e7-7b6e-4388-b0f3-8f174693f331">

**Additional context**
A force hydration wrapper would also be helpful. Please suggest way to implement and I can work on it.

**Comment by harlan-zw** [comment]
Hi @sauravbv 

Thanks for the issue and the contribution! I'll try and look at this tomorrow.

**Comment by sauravbv** [comment]
Thank you @harlan-zw

**Comment by sauravbv** [comment]
> Hi @sauravbv
> 
> Thanks for the issue and the contribution! I'll try and look at this tomorrow.

Thank you @harlan-zw

**Comment by sauravbv** [comment]
@harlan-zw got a chance to look at this ? Just wanted to understand if this is a bug or its intended to work this way.

**Comment by harlan-zw** [comment]
Hey @sauravbv. Just had a chance to look, it was a pretty annoying bug, basically because Nuxt now awaits all suspended components when rendering, it would cause the entire page to stall in hydrating (or at least all nested components).

I've fixed that up as well as added route rules support.

Let me know if you need help with anything else.

**Comment by sauravbv** [comment]
@harlan-zw Thanks for the quick update, But I am getting the following error when I update the package and start local nuxt server.

**Environment details**
nuxt: "^3.7.1"
node: 16.20.0
package version: 1.3.0

I also referred the updated release notes, is `delayHydration` config in `routeRules` mandatory? Will it still work with old `include` and `exclude`? 


<img width="1465" alt="image" src="https://github.com/harlan-zw/nuxt-delay-hydration/assets/41701284/eae4e6a6-93bd-420a-b2ff-5a50bd382d3a">

**Comment by harlan-zw** [comment]
Looks like a Nuxt version issue, though I did some more testing and it seems like this `getRouteRules` function is throwing some 404's with the new app manifest, so I've updated it to use some different code. Try out v1.3.1

Yes, `include` and `exclude` will keep working.

**Comment by sauravbv** [comment]
Thanks for the quick updates and fixed @harlan-zw. It works fine now ✌️

I wanted to follow up on the below issue. Can something like `<force-hydration>` wrapper component be achieved in nuxt 3 as it uses vue 3+ ? I wanted to know how we could achieve this so I can try and contribute. There was a request created for this couple of years back, But back then nuxt wasn't running on vue 3.
https://github.com/harlan-zw/nuxt-delay-hydration/issues/2

This can be useful where we would want to wrap the layouts with `<LazyHydration>` component but can easily force hydrate few components which is required to hydrate on client side immediately.

**Comment by harlan-zw** [comment]
So it seems like Vue never added support for this, I guess it's something for Vapor mode to solve. 

I think the only possible way to handle this is with using client components within server components which was recently supported in Nuxt behind some experimental flags
