### ISSUE TITLE
DelayHydration component no longer registered since v1.3.0

### ISSUE THREAD

**Issue by MooseSaeed** [harlan-zw/nuxt-delay-hydration#40]
**Describe the bug**
Since [v1.3.0](https://github.com/harlan-zw/nuxt-delay-hydration/releases/tag/v1.3.0), the `DelayHydration` component is no longer automatically registered.

**Additional context**
I'm using Nuxt 3.8.1 and DelayHydration component is automatically registered only until nuxt-delay-hydration@1.2.3. When I upgrade to 1.3.0, the component is not registered anymore.

**Comment by harlan-zw** [comment]
Hi, thanks for the issue.

This seems to be fixed in v1.3.3

**Comment by MooseSaeed** [comment]
Just tested, it is fixed. Thank you for your awesome work
