### ISSUE TITLE
Layout jump when hydration happens

### ISSUE THREAD

**Issue by andrevferreiraa** [harlan-zw/nuxt-delay-hydration#46]
When I use "mount" mode and the whole page hydrates, there's a quick jump to the footer and back to the header. It's like the whole page (except the component in the layout), disappears for half a second. 

Anything I can do to prevent this?

**Comment by harlan-zw** [comment]
This would be related to your code, you need to make sure you're not showing / hiding components during the mount lifecycle. The SSR response should match exactly to the hydrating and hydrated HTML.
