### ISSUE TITLE
Wrong scroll behaviour when module is manual

### ISSUE THREAD

**Issue by agracia-foticos** [harlan-zw/nuxt-delay-hydration#47]
**Describe the bug**
Open the url with chrome in mobile simulation

**To Reproduce**
Open
https://stackblitz.com/edit/nuxt-starter-sawwhz?file=README.md
Scroll as follows.
Click on the link and drag the screen. You can check that the link is clicked, when it shouldn't, it should scroll without launching the click event

**Expected behavior**
The click should not be issued, but simply the scroll

**Comment by harlan-zw** [comment]
The reproduction isn't clear, could you check that it's accurate? Seems like it shouldn't be manual unless you provide the DelayHydration component.

**Comment by harlan-zw** [comment]
> There is very short period of time when you can reproduce it, right after page is rendered. We have the same issue.

Can you provide a reproduction?

**Comment by harlan-zw** [comment]
Should be fixed in v1.3..6 🤞
