### ISSUE TITLE
Different behaviour on different mobile devices

### ISSUE THREAD

**Issue by andrevferreiraa** [harlan-zw/nuxt-delay-hydration#48]
On my project, i'm using "mount" mode. But I disabled the delay hydration for a few specific pages. I check the debug log, and it is in fact disabled. Here's the weird part:

On my iPhone, it all works perfectly and it is disabled. But on an android, it's still there. The page is still waiting for using interaction. 

Any reason why this could be happening?

**Comment by andrevferreiraa** [comment]
I realize now that on development everything works fine. But in production mode, the routeRules are ignored completely and thus, delay hydration is always enabled.

**Comment by harlan-zw** [comment]
I have tested opt-ing out of the hydration using inline route rules and it seems to be behaving correctly. I have also pushed up improvements around the route rules in the latest version though.

Can you provide a [reproduction](https://stackblitz.com/edit/nuxt-starter-rfoovf?file=nuxt.config.ts) if you'd like further help.
