### ISSUE TITLE
Error: Cannot find module '@nuxt/kit'

### ISSUE THREAD

**Issue by renestalder** [harlan-zw/nuxt-delay-hydration#5]
**Describe the bug**
Upgrading to 0.3.0 or later, will show a Nuxt error when I try to start the nuxt project.

```sh
   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                             │
   │   ✖ Nuxt Fatal Error                                                                                                        │
   │                                                                                                                             │
   │   Error: Cannot find module '@nuxt/kit'                                                                                     │
   │   Require stack:                                                                                                            │
   │   - /project_path/node_modules/nuxt-delay-hydration/dist/index.js                                                           │
   │                                                                                                                             │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I removed the node_modules folder and installed everything from scratch, but it still comes up, even though I see it in the dependencies of the nuxt-delay-hydration project.

npm ls shows following:

```ah
➜  project git:(master) ✗ npm ls @nuxt/kit   
project@1.0.0 /project
└─┬ nuxt-delay-hydration@0.3.2
  └── UNMET DEPENDENCY @nuxt/kit@npm:@nuxt/kit-edge@latest

npm ERR! missing: @nuxt/kit@npm:@nuxt/kit-edge@latest, required by nuxt-delay-hydration@0.3.2
```

Has it maybe something to do how nuxt/kit is referenced with the npm prefix in the dependencies?

**To Reproduce**
–

**Expected behavior**
@nuxt/kit should automatically be installed aliong

**Screenshots**
–

**Additional context**
–

**Comment by renestalder** [comment]
For reference (just found it0:

https://github.com/nuxt/module-builder/issues/26

**Comment by harlan-zw** [comment]
Hey @renestalder 

Can you confirm your node version? If you're using <= 12 can you make sure you upgrade

**Comment by harlan-zw** [comment]
> > Can you confirm your node version? If you're using <= 12 can you make sure you upgrade
> 
> Yep, saw that note in some other ticket, but I'm using version 14 upwards, so that wasn't it, unless you know this still happens with certain v14 version ranges.

I'm trying to get to the bottom of the issue I have been able to replicate it, but can't seem to pin-point the exact issue.

**Comment by fogine** [comment]
I'm getting build error

>   ✖ Nuxt Fatal Error 
 Error: Cannot find module 'node:fs' 
 Require stack:
- /home/fogine/Projects/node/beat-market-frontend/node_modules/@nuxt/kit/dist/index.mjs
