### ISSUE TITLE
Module is disabled automatically when generating SSG Nuxt app 

### ISSUE THREAD

**Issue by austin-agronick** [harlan-zw/nuxt-delay-hydration#50]
**Describe the bug**
The README states "Requirement: Progressively enhanced SSR or SSG Nuxt app.", but when I try to generate my SSG Nuxt app I get "disabling module". Here is the relevant lines from the command output:
```
> nuxt generate

Nuxt 3.11.2 with Nitro 2.9.6
ℹ Using Nitro server preset: static

 WARN  'nuxt-delay-hydration' will only work for SSR apps, disabling module.
```

**To Reproduce**
1. Run `pnpm generate`

**Expected behavior**
Generate site using nuxt-delay-hydration module.

**Comment by harlan-zw** [comment]
I wasn't able to replicate the issue just running `nuxt generate`. Can you double-check you haven't set `ssr: false` in your Nuxt config.

**Comment by austin-agronick** [comment]
ssr is disabled, its a ssg nuxt app

**Comment by harlan-zw** [comment]
You don't need to specify this in the config if you're using nuxt generate

**Comment by austin-agronick** [comment]
I am serving static files in production using Django, so I can’t use SSR. Is nuxt-delay-hydration still relevant for static sites without SSR?

**Comment by harlan-zw** [comment]
I'm not saying to switch to ssr I'm just saying you don't need to disable it to use SSG, you'll have more accurate dev environment.
