### ISSUE TITLE
useNuxtApp() helper returns type unknown

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [harlan-zw/nuxt-delay-hydration#52]
# Describe the bug
The `nuxt-delay-hydration` package versions v1.3.4 or above cause errors with the generated Nuxt types. Downgrading to version `1.3.3` resolves the issue.

# To Reproduce
- Create a new Nuxt application.
- Create a plugin and expose some variables through `provider`
- Install nuxt-delay-hydration version v1.3.4 or above.
- Reference the exposed variables in `index.vue` page
- Error will occur saying "`${var name} is of type 'unknown' ts(18046)`"

## Expected Behavior:
The application should function without errors with the latest version of `nuxt-delay-hydration`.

## Actual Behavior:
Installing `nuxt-delay-hydration` versions `v1.3.4` or above causes errors in the generated Nuxt types.

## Workaround:
Downgrading `nuxt-delay-hydration` to version `1.3.3` resolves the issue.

# Screenshots
## Issue:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/49c84a33-2656-44a3-b92e-4eb620b8abd1"><br/>

<img width="435" alt="image" src="https://github.com/user-attachments/assets/0f67e0e7-aebb-47b7-bc20-3c5857af4927">

## Fix:
<img width="268" alt="image" src="https://github.com/user-attachments/assets/d7cd857e-93c2-4e10-b99c-9e7abab78625"><br/>

<img width="935" alt="image" src="https://github.com/user-attachments/assets/4a32cedf-0be1-4f69-b638-d867fa14a594">

**Comment by Vahagn-Zaqaryan** [comment]
I commented here as well
https://github.com/nuxt/nuxt/issues/20390#issuecomment-2246047349

**Comment by dipbhi** [comment]
A work around until this issue is fixed: https://stackoverflow.com/a/76163467/140164

**Comment by PedrooLska** [comment]
I have the same problem. I've done all the procedures in the community and none of them have worked.

**Vue**: Latest
**Nuxt**: 3.13.0
**Typescript**: 5.5.4
**VSCode** 1.92.2

**Comment by PedrooLska** [comment]
> A work around until this issue is fixed: https://stackoverflow.com/a/76163467/140164

Thanks my friend!

I've just tested it here and it worked perfectly, follow the code below.

`

`

**Comment by harlan-zw** [comment]
I've tried to replicate this but I don't think this is an issue with this module. It's likely due to the module depending on a later version of something upstream that is causing issue.

The module itself registers a plugin that does not inject anything on to Nuxt App.

I'll need to close for now but if anyone else lands on this please check the above resources.
