### ISSUE TITLE
Page links automatically triggered on Hydration event

### ISSUE THREAD

**Issue by milelazar** [harlan-zw/nuxt-delay-hydration#53]
**Describe the bug**
I am using Nuxt version 3.12.4 and nuxt-delay-hydration version 1.3.5. If mouse cursor is over a link on page load, when "Hydration event" is called, link is automatically triggered so you end up on different page.

It is a clean Nuxt install so there are no custom functions that might create that issue.
Delay hydration mode is set to "mount".

Works fine in dev mode. The problem only appears on production build.

**To Reproduce**
1. Install Nuxt and nuxt-delay-hydration plugin
2. Set delayHydration.mode config to "mount"
3. Build and run production version
4. Place cursor over any link and refresh the page
5. If you move the mouse before "Hydration event timeout" is logged, Hydration mouse event is triggered and page gets redirected

**Expected behavior**
Link should not be clicked/triggered automatically on Hydration event

**Screenshots**
[screen-capture.webm](https://github.com/user-attachments/assets/ebb9ff67-20f9-4b70-9cbc-647cf4321523)

**Comment by pavloniym** [comment]
Confirmed!
As a tmp variant - revert to `1.3.3` version
