### ISSUE TITLE
On click events and links getting triggered on scroll primarily on mobile devices. 

### ISSUE THREAD

**Issue by gsriram24** [harlan-zw/nuxt-delay-hydration#54]
**Describe the bug**
Whenever we add the delay hydration package, open a page on a mobile device, and try to scroll, the links are triggered. 
This is more prevalent in android phones. Even if delay hydration is disabled in the manual mode, this happens. Only time it does not is if we remove the package itself. 

**To Reproduce**
1. Open this link (https://stackblitz.com/edit/nuxt-starter-dedhnc?file=app.vue). 
2. Run the app, and preview on new tab, and emulate on a mobile device (preferably android)
3. Try scrolling with the pointer on the big box. 
4. Google gets opened with no option to go back. 

**Expected behavior**
The link trigger must not happen. 

**Additional context**
I also notice it's the case with onclick events being triggered too. I have also tried all versions starting from 1.2.5 till the latest. I have kept it at 1.3.2 here in this example to avoid the link auto navigation issue. https://github.com/harlan-zw/nuxt-delay-hydration/issues/53

**Comment by harlan-zw** [comment]
Should be fixed in v1.3..6 🤞
