### ISSUE TITLE
Script added in `manual` mode even if `DelayHydration` component is not used

### ISSUE THREAD

**Issue by sauravbv** [harlan-zw/nuxt-delay-hydration#56]
**Description**

Some help or suggestions are required so I can work on the code changes and raise a PR for this.
I have tried few ways in the package by setting a global state variable in the DelayHydration.mjs but does not work.
Happy to discuss more

The delay hydration and replayClick scripts are added to the rendered HTML even if the `<DelayHydration>` component is not used. 
I have a use case where I am wrapping the entire page layout with <DelayHydration> based on a condition (Check attached screenshot)
When the v-else part is rendered the scripts are still added to the HTML output from nitro. 
This is a problem especially when replayClick is enabled and causes the scroll touchEvent issue on mobile devices which was reported below 
https://github.com/harlan-zw/nuxt-delay-hydration/issues/54
https://github.com/harlan-zw/nuxt-delay-hydration/issues/47

**To Reproduce**
Please check the below stackblitz 
https://stackblitz.com/edit/nuxt-starter-8agcnh?file=app.vue
Manual mode and <DelayHydration> is not used, but the scripts is being injected and replayClick is triggering due to this

**Expected behavior**
If the mode is `manual` and the <DelayHydration> component is not used, delay hydration scripts shouldn't be appended in the nitro plugin. 

**Screenshots**
<img width="484" alt="image" src="https://github.com/user-attachments/assets/8863c05c-795d-489f-8ed8-2c704e06409f">

**Additional context**
I have tried with some code changes in the package where I wanted to set a global state in the DelayHydration.mjs based on which scripts are appended or not in the nitro plugin. 
Include or exclude filters won't help here as its a common page and delay hydration is toggled based on a condition.

**Comment by sauravbv** [comment]
@harlan-zw any suggestions / update on this?

**Comment by harlan-zw** [comment]
Hey, thanks for the detailed issue.

I've pushed up a [fix](https://github.com/harlan-zw/nuxt-delay-hydration/commit/0390a2b419c3ce1b3872742ad4994c2e671dd512) in v1.3.7.

Let me know if you have any issues with it, but I think this is the easiest way to solve the issue.

**Comment by sauravbv** [comment]
Thank you @harlan-zw 
I will test it out and reply here.
