### ISSUE TITLE
FATAL nuxtCtx.set is not a function v0.3.4

### ISSUE THREAD

**Issue by PawFV** [harlan-zw/nuxt-delay-hydration#7]
Re opens #6 the error persists.

@harlan-zw hey updated the package but the probleme persists, I'm having the exact same error.

As it might be really hard to replicate (I'm working with a huge Nuxt app) we can go to a debugging session in my env if you like, just lmk anything I can do, if this module works as I think it works it will solve a lot of problems we have currently because of huge hydration.

Even with a lot of techniques like lazy-loading 3rd party, optimizing plugins, lazy hydrate and so on we still can't get a good lighthouse score on mobile, half of our bundle size LH say's it's unused, we can't technically remove GRAPHQL from our bundle, idk what the hell is that metric but anyways...

**Comment by harlan-zw** [comment]
Thanks @PawFV, I'll re-open the other ticket and continue discussions there
