### ISSUE TITLE
nuxtCtx.tryUse is not a function 

### ISSUE THREAD

**Issue by procrates** [harlan-zw/nuxt-delay-hydration#9]
**Describe the bug**

```
 FATAL  nuxtCtx.tryUse is not a function                               08:56:01

  at tryUseNuxt (node_modules/@nuxt/kit/dist/index.mjs:54:18)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:601:14)
  at node_modules/nuxt-delay-hydration/dist/module.cjs:2:53
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────╮
   │                                                 │
   │   ✖ Nuxt Fatal Error                            │
   │                                                 │
   │   TypeError: nuxtCtx.tryUse is not a function   │
   │                                                 │
   ╰─────────────────────────────────────────────────╯
```

**To Reproduce**

I am trying to use this on an exsisting project running in full static, Nuxt 2. 
I have gotten this error before on other projects while using Nuxt 3.

**Expected behavior**

**Screenshots**

**Additional context**
Dont really know how to describe it futher, when i have time I will make a minimal reproduction. 

Edit: 
```
❯ npm why @nuxt/kit
@nuxt/kit@3.0.0-rc.8
node_modules/@nuxt/kit
  @nuxt/kit@"^3.0.0-rc.8" from the root project
  @nuxt/kit@"^3.0.0-rc.8" from nuxt-delay-hydration@0.4.5
  node_modules/nuxt-delay-hydration
    nuxt-delay-hydration@"^0.4.5" from the root project

@nuxt/kit@0.6.4
node_modules/@nuxtjs/sanity/node_modules/@nuxt/kit
  @nuxt/kit@"0.6.4" from @nuxtjs/sanity@0.10.0
  node_modules/@nuxtjs/sanity
    @nuxtjs/sanity@"^0.10.0" from the root project
```

But if anyone know would be of great help! Thanks!

And love the concept of the module! Would be great to show off awesome lighthouse stats to clients!

**Comment by harlan-zw** [comment]
Hey @procrates 

This issue is related to different @nuxt/kit's using different versions of [unctx](https://github.com/unjs/unctx). 

Couple of ways to fix this:
- update the sanity module if possible
- update your package manager to use `unctx@^2.0.1.` (see https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/ or https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

**Comment by dannyk08** [comment]
Hey @harlan-zw 

I'm having pretty much the same issue as OP.
Could you elaborate more on what the right setup should look like?

```.json
"resolutions": {
    "unctx": "unctx@^2.0.1"
},
```

Thanks!

**Comment by harlan-zw** [comment]
> Hey @harlan-zw
> 
> I'm having pretty much the same issue as OP. Could you elaborate more on what the right setup should look like?
> 
> ```json
> "resolutions": {
>     "unctx": "unctx@^2.0.1"
> },
> ```
> 
> Thanks!

I think like this

```
"resolutions": {
    "unctx": "2.0.1"
},
```

Try upgrading nuxt / all modules if you're still having this though, they should have resolved it by now

**Comment by dannyk08** [comment]
Thank you @harlan-zw !
Unfortunately upgrading modules is not an easy option. But I'll test which changes can help without breaking anything crucial
